apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: sunilsahu0123/hello-world-spring-boot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
